name: CICD
run-name: ${{ github.actor }} is running CI
on: [push, pull_request]

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/ci-cd-2024-dhbw-hdh/daniel.schwager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM install
        run: npm install
      - name: run test
        run: npm run test

  deploy-github-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            "ghcr.io/ci-cd-2024-dhbw-hdh/daniel.schwager:latest"

  deploy-k8:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Create namespace
        run: kubectl create namespace daniel-schwager --dry-run=client -o yaml | kubectl apply -f -
          
      - name: create image registry secret for kubernetes
        uses: Azure/k8s-create-secret@v1.1
        with:
          namespace: daniel-schwager
          container-registry-url: ghcr.io
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          secret-name: regcred

      - name: deploy deployment and service
        uses: Azure/k8s-deploy@v4
        with:
          namespace: daniel-schwager
          manifests: |
            .kubernetes/deployment.yaml
            .kubernetes/service.yaml
          imagepullsecrets: |
            regcred          